services:
  postgres:
    image: postgres:16-alpine
    container_name: marquesuahora-postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-marquesuahora}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-VS_nMw5Fsv97nNfmT04xbQp8PbfJbMdF}
      POSTGRES_DB: ${POSTGRES_DB:-marquesuahora_db}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-marquesuahora} -d ${POSTGRES_DB:-marquesuahora_db}"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: marquesuahora-redis
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD:-8c584b308c8777897fb6a5ccbab77a7827966554c0507c6e1ec858580ad3ebe4}
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD:-8c584b308c8777897fb6a5ccbab77a7827966554c0507c6e1ec858580ad3ebe4}", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  redis_data:
